---
namespace: geerlingguy
name: php_roles
description: An elegant collection of roles for PHP automation.
version: "0.9.2"
readme: README.md
authors:
  - geerlingguy (https://www.jeffgeerling.com/)
dependencies: []
license:
  - MIT
tags:
  - php
  - apache
  - lamp
  - lemp
  - nginx
  - apache
  - debian
  - ubuntu
  - centos
  - amazon
  - linux
  - rhel
  - fedora
  - drupal
  - wordpress
  - laravel
repository: https://github.com/geerlingguy/ansible-collection-php
documentation: https://github.com/geerlingguy/ansible-collection-php
# homepage: ""
issues: https://github.com/geerlingguy/ansible-collection-php/issues
